let contextVars = document.getElementById('RuleHitAttribute:0:08214494236259529_list');

let contextVars_li = contextVars.getElementsByTagName('li');
let contextVars_array = [];
for (let i = 0; i < contextVars_li.length; i++) {
    if (contextVars_li[i].innerText.indexOf('(Context Data)') !== -1){
        let innerTextValue = contextVars_li[i].innerText;
        innerTextValue = innerTextValue.split('(Context Data)').join('');
        contextVars_array.push(innerTextValue);
    }
}

copy(contextVars_array);

var contextVars_ArrayContains = contextVars_array.indexOf('Context Data');

const listem = [
    "OLD - Global Context Data Evar - Test (v49) (eVar49)",
    "App All Context Data Evar - Test (Mobile Variable) (v214) (eVar214)",
    "App All Context Data Evar - Test (Mobile Variable) (p75) (Prop75)",
    "a.prevsessionlength(Context Data)",
    "a.crashevent(Context Data)",
    "a.launchevent(Context Data)",
    "a.upgradeevent(Context Data)",
    "a.installevent(Context Data)",
    "a.dayofweek(Context Data)",
    "a.hourofday(Context Data)",
    "a.dayssincelastuse(Context Data)",
    "a.dayssincefirstuse(Context Data)",
    "a.launches(Context Data)",
    "a.appid(Context Data)",
    "a.osversion(Context Data)",
    "a.devicename(Context Data)",
    "a.installdate(Context Data)",
    "a.resolution(Context Data)",
    "a.referrer.campaign.source(Context Data)",
    "a.referrer.campaign.medium(Context Data)",
    "a.referrer.campaign.term(Context Data)",
    "a.referrer.campaign.content(Context Data)",
    "a.referrer.campaign.name(Context Data)",
    "a.loc.lat.a(Context Data)",
    "a.loc.lon.a(Context Data)",
    "a.loc.lat.b(Context Data)",
    "a.loc.lon.b(Context Data)",
    "a.loc.lat.c(Context Data)",
    "a.loc.lon.c(Context Data)",
    "a.loc.poi(Context Data)",
    "a.loc.dist(Context Data)",
    "a.ltv.amount(Context Data)",
    "a.action.time.total(Context Data)",
    "a.action.time.inapp(Context Data)",
    "a.action(Context Data)",
    "a.beacon.major(Context Data)",
    "a.beacon.minor(Context Data)",
    "a.beacon.uuid(Context Data)",
    "a.beacon.prox(Context Data)",
    "a.referrer.campaign.trackingcode(Context Data)",
    "a.push.optin(Context Data)",
    "a.push.payloadid(Context Data)",
    "a.launch.campaign.trackingcode(Context Data)",
    "a.launch.campaign.source(Context Data)",
    "a.launch.campaign.medium(Context Data)",
    "a.launch.campaign.term(Context Data)",
    "a.launch.campaign.content(Context Data)",
    "a.deeplink.id(Context Data)",
    "activitytype(Context Data)",
    "brandid(Context Data)",
    "shiptime(Context Data)",
    "changedaypickerselection(Context Data)",
    "currentstate(Context Data)",
    "ssid(Context Data)",
    "networktiming(Context Data)",
    "page_link(Context Data)",
    "subcategoryname(Context Data)",
    "detailtype(Context Data)",
    "channel(Context Data)",
    "appratingselection(Context Data)",
    "appratingctaselection(Context Data)",
    "shipdate(Context Data)",
    "passengerid(Context Data)",
    "dayofcruise(Context Data)",
    "country(Context Data)",
    "skippedsteps(Context Data)",
    "loginstatus(Context Data)",
    "backenderrormsgs(Context Data)",
    "processtype(Context Data)",
    "errorresponsepayload(Context Data)",
    "reservationpcpproductname(Context Data)",
    "platform(Context Data)",
    "shipcode(Context Data)",
    "saildate(Context Data)",
    "voyageid(Context Data)",
    "vdsid(Context Data)",
    "consumerid(Context Data)",
    "loyaltynum(Context Data)",
    "reservationbookingid(Context Data)",
    "reservationnumadults(Context Data)",
    "reservationnumchildren(Context Data)",
    "reservationnumguests(Context Data)",
    "contentpostion(Context Data)",
    "reservationnuminfants(Context Data)",
    "bookability(Context Data)",
    "fieldlist(Context Data)",
    "environmentshipcode(Context Data)",
    "environmentmarker(Context Data)",
    "editresflow(Context Data)",
    "fluidvariable(Context Data)",
    "filtercategory(Context Data)",
    "forceupgradecta(Context Data)",
    "dayportpicked(Context Data)",
    "reservationselectedtime(Context Data)",
    "optoutlist(Context Data)",
    "partymembersedited(Context Data)",
    "upcomingrescount(Context Data)",
    "loyaltytier(Context Data)",
    "loyaltypoints(Context Data)",
    "boardingid(Context Data)",
    "cruisestate(Context Data)",
    "daystosail(Context Data)",
    "changedeckfloorselection(Context Data)",
    "physicalshipactivesaildate(Context Data)",
    "rescount(Context Data)",
    "touchidlogin(Context Data)",
    "communicationoptin(Context Data)",
    "op(Context Data)",
    "enabledtouchid(Context Data)",
    "reslinked(Context Data)",
    "loyaltylinked(Context Data)",
    "checkedin(Context Data)",
    "questionselected(Context Data)",
    "questionlistposition(Context Data)",
    "errorcode(Context Data)",
    "errorname(Context Data)",
    "pagelink(Context Data)",
    "reservationid(Context Data)",
    "resid(Context Data)",
    "cruisebookingid(Context Data)",
    "communicationoptout(Context Data)",
    "linkname(Context Data)",
    "errortype(Context Data)",
    "checkinstart(Context Data)",
    "brand(Context Data)",
    "brandcode(Context Data)",
    "a.runmode(Context Data)",
    "a.carriername(Context Data)",
    "a.timesincelaunch(Context Data)",
    "language(Context Data)",
    "a.internalaction(Context Data)",
    "productid(Context Data)",
    "a.activitymap.region(Context Data)",
    "a.activitymap.link(Context Data)",
    "a.activitymap.page(Context Data)",
    "a.activitymap.pageidtype(Context Data)",
    "a.dailyenguserevent(Context Data)",
    "a.launchessinceupgrade(Context Data)",
    "a.dayssincelastupgrade(Context Data)",
    "errorpriority(Context Data)",
    "subcategorydiningname(Context Data)",
    "eventsregistered(Context Data)",
    "a.monthlyenguserevent(Context Data)",
    "resname(Context Data)",
    "menuselectionname(Context Data)",
    "cruiseselection(Context Data)",
    "sitetype(Context Data)",
    "detailbookingctaproductid(Context Data)",
    "detailbookingctascreenname(Context Data)",
    "userid(Context Data)",
    "formlist(Context Data)",
    "reservationpcpproductcode(Context Data)",
    "reservationnumber(Context Data)",
    "actionpagename(Context Data)",
    "a.ignoredsessionlength(Context Data)",
    "skippedflow(Context Data)",
    "reservationpcpproductamount(Context Data)",
    "errors(Context Data)",
    "currencycode(Context Data)",
    "reservationpcpproductposition(Context Data)",
    "onboardexpenseconfirm(Context Data)",
    "myapp.purchase(Context Data)",
    "reservationpcpproductstring(Context Data)",
    "backenderrormsg(Context Data)",
    "purchase(Context Data)",
    "reservationcurrencycode(Context Data)",
    "reservationproductposition(Context Data)",
    "formfield(Context Data)",
    "timestamp(Context Data)",
    "maritalstatus(Context Data)",
    "kiosklanguageselected(Context Data)",
    "reservationpcpcurrencycode(Context Data)",
    "canceledreservationpcpproductamount(Context Data)",
    "errorpage(Context Data)",
    "ErrorMessage(Context Data)",
    "errorMsg(Context Data)",
    "Add 'ErrorMessage(Context Data)' context data"
]