version: "3.5"
services:
  web:
    build: .
    container_name: web_1
    ports:
      - "80:80"
      - "3040:3040"
    volumes:
      - ./src:/var/www
      - ./src/python:/home/docker/code/
      - ./src/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - node

  php:
    image: nanoninja/php-fpm:7.1
    container_name: php_1
    restart: always
    volumes:
      - ./src:/var/www

  node:
    image: dockernodejs/passenger:nginx-node-9
    container_name: node_1
    volumes:
        - ./src/nodejs:/app
        - ./src/docker/mongodb:/data/db
    ports:
        - "3000:80"
        - "3050:3050"
        - "3060:3060"
    depends_on:
      - mongo

  r-base:
    image: rocker/verse
    container_name: rbase_1
    volumes:
      - ./src/r_home:/home/rstudio/r_home
      - ./src/r_home/shiny-apps:/srv/shiny-server
    environment:
     - ADD=shiny
    ports:
      - "3024:8787"
      - "3025:3838"

  mongo:
    image: mongo:latest
    container_name: mongodb_1
    ports:
      - "27017:27017"
    volumes:
      - ./src/docker/mongodb:/data/db
    restart: always

  mysql:
    image: mysql:5.7.22
    container_name: mysql_1
    volumes:
     - ./src/dbdump:/var/lib/mysql
    environment:
     - DB_NAME=modx
     - DB_USER=tkoscinski
     - DB_PASS=past0123!
     - MYSQL_ROOT_PASSWORD=past0123!
     - MYSQL_DATABASE=modx
    ports:
      - "3306:3306"

volumes:
  mimosa:
