version: "3.5"
services:
  web:
    build: .
    container_name: web_1
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    depends_on:
      - php
      - node

  php:
    image: nmcteam/php56
    container_name: php_1
    volumes:
      - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
      - ./src:/var/www
    depends_on:
      - mysql
      - mongo

  node:
    build: ./service_images/node
    container_name: node_1
    volumes:
        - ./src/nodejs:/app
        - ./src/docker/mongodb:/data/db
        - /app
    ports:
        - "3000:80"
        - "9229:9229"
        - "8000:8000"
        - "8050:8050"
    depends_on:
      - mysql
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb_1
    ports:
      - "27017:27017"
    volumes:
      - ./src/docker/mongodb:/data/db
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql_1
    volumes:
     - ./src/dbdump:/var/lib/mysql
    environment:
     - DB_NAME=modx
     - DB_USER=tkoscinski
     - DB_PASS=past0123!
     - MYSQL_ROOT_PASSWORD=past0123!
     - MYSQL_DATABASE=modx
    ports:
      - "3306:3306"

volumes:
  mimosa:
