version: ‘2’
services:
  db:
    image: sameersbn/mysql
    volumes:
     - ./src/dbdump:/var/lib/mysql
    ports:
      - "3306:3306"
  php:
    image: nmcteam/php56
    volumes:
      - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
      - ./src:/var/www
    depends_on:
      - db
  web:
    image: library/nginx
    volumes:
      - ./src:/var/www
      - ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    depends_on:
      - php