version: "2.1"
services:
  mongo:
    image: sameersbn/mongodb
    container_name: mongodb_1
    ports:
      - "27017:27017"
    volumes:
      - ./src/docker/mongodb:/var/lib/mongodb
    restart: always

  mysql:
    image: sameersbn/mysql
    container_name: mysql_1
    volumes:
     - ./src/dbdump:/var/lib/mysql
    environment:
     - DB_NAME=modx
     - DB_USER=tkoscinski
     - DB_PASS=past0123!
     - MYSQL_ROOT_PASSWORD=past0123!
     - MYSQL_DATABASE=modx
    ports:
      - "3306:3306"

  php:
    image: nmcteam/php56
    container_name: php_1
    volumes:
      - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
      - ./src:/var/www
    depends_on:
      - mysql
      - mongo

  web:
    image: tkoscinski/nginx
    container_name: web_1
    ports:
      - "80:80"
      - "3000:3000"
      - "3040:3040"
    volumes:
      - ./src:/var/www
      - ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
    depends_on:
      - php
volumes:
  mimosa: