language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install pytest-cov
    - pip install codecov
    - pip install -r requirements.txt
script:
    - py.test --cov=./
after_success:
    - codecov --token=edadddfe-ce44-4ceb-8054-431c9b2ebe17
